### PR TITLE
tic tac toe command

### PR DESCRIPTION
**Pull request by lunispang**
Added: tic tac toe command
Changed: reorder the imports alphabetically because i couldn't take it anymore

unrelated:
also you should probably add a testing branch or something

### CODE REVIEW

**Comment by lunispang** [comment]
oopsies lsp broke, will fix broken stuff

**Comment by lunispang** [comment]
should be fixed now, don't know what broke rustanalyzer

**Comment by lunispang** [comment]
please work

**Comment by mostlymaxi** [comment]
lgtm

**Pull request merged**
